version: '3'
services:

  consul:
    image: consul:0.9.3

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    volumes:
      - /home/data:/data
    environment:
      - MINIO_ACCESS_KEY=hackathon # minio user
      - MINIO_SECRET_KEY=hackathon2017 # minio password
      - MINIO_REGION=us-east-1 # region for storage buckets (see amazon S3 specs)
      - MINIO_BROWSER=on # activate minio http browser
    command: ["minio","server","/data"] 

  swarm_visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
